"use client";
/* eslint-disable @next/next/no-img-element -- user-uploaded Supabase and local blob preview URLs are intentionally dynamic */

import dynamic from "next/dynamic";
import { FormEvent, useEffect, useState } from "react";
import { countryFeatures, flag } from "./globe-scene";
import { formatMoney, getMinimumNextStake } from "@/lib/pricing";
import type { CountryState } from "@/lib/types";
import { getBrowserClient } from "@/lib/supabase";
import { resizeImageFile } from "@/lib/image";
import { analytics, fileSizeBucket } from "@/lib/analytics/posthog-client";
import { MinimalFooter } from "@/components/minimal-footer";
import { HomepageFaq } from "@/components/homepage-faq";

const Globe = dynamic(() => import("./globe-scene").then((m) => m.GlobeScene), { ssr: false });
type Bidder = { brand_id: string; total_amount: number; brand: { name: string; logo_url: string; website_url: string } | null };
function blankStates() { return Object.fromEntries(countryFeatures.map((c) => [c.iso3, { iso2: c.iso2, iso3: c.iso3, name: c.name, centroid_lat: 0, centroid_lng: 0, current_stake: 0, brand: null } satisfies CountryState])); }

export function GlobeExperience() {
  const [states, setStates] = useState<Record<string, CountryState>>(blankStates); const [selected, setSelected] = useState<string>(); const [claiming, setClaiming] = useState(false); const [notice, setNotice] = useState(""); const [bidders, setBidders] = useState<Bidder[]>([]); const [viewers, setViewers] = useState(0);
  useEffect(() => { const params = new URLSearchParams(location.search); const query = params.get("country")?.toUpperCase(); if (query) queueMicrotask(() => setSelected(query)); const bidId = params.get("bid_id"); if (params.get("checkout") === "returned" && query && bidId) { analytics.paymentReturned({ country_code: query, bid_id: bidId }); analytics.paymentPendingViewed({ country_code: query, bid_id: bidId }); void pollBidStatus(bidId, query); } fetchGlobe(setStates); const supabase = getBrowserClient(); if (!supabase) return; let debounce: ReturnType<typeof setTimeout>; const channel = supabase.channel("country_updates").on("postgres_changes", { event: "UPDATE", schema: "public", table: "countries" }, () => { clearTimeout(debounce); debounce = setTimeout(() => fetchGlobe(setStates), 250); }).subscribe(); return () => { clearTimeout(debounce); void supabase.removeChannel(channel); }; }, []);
  useEffect(() => { if (!selected) { queueMicrotask(() => { setBidders([]); setViewers(0); }); return; } fetch(`/api/countries/${selected}`).then((r) => r.json()).then((d) => setBidders(d.bidders || [])).catch(() => setBidders([])); const supabase = getBrowserClient(); if (!supabase) return; const presence = supabase.channel(`viewing:${selected}`, { config: { presence: { key: crypto.randomUUID() } } }); presence.on("presence", { event: "sync" }, () => setViewers(Object.keys(presence.presenceState()).length)).subscribe(async (status) => { if (status === "SUBSCRIBED") await presence.track({ online_at: new Date().toISOString() }); }); return () => { void supabase.removeChannel(presence); }; }, [selected]);
  const current = selected ? states[selected] : undefined; const claimed = Object.values(states).filter((s) => s.current_stake > 0).length; const total = Object.values(states).reduce((n, s) => n + Number(s.current_stake || 0), 0);
  function select(code: string) { const country = states[code]; if (country) analytics.countrySelected({ country_code: code, country_name: country.name, is_claimed: Number(country.current_stake) > 0, current_stake: Number(country.current_stake), minimum_next_stake: getMinimumNextStake(Number(country.current_stake)) }); setSelected(code); setClaiming(false); const params = new URLSearchParams(location.search); params.set("country", code); history.replaceState(null, "", `/?${params}`); if (navigator.vibrate) navigator.vibrate(8); }
  function openClaim(country: CountryState) { analytics.claimOpened({ country_code: country.iso3, is_claimed: Number(country.current_stake) > 0, current_stake: Number(country.current_stake), minimum_next_stake: getMinimumNextStake(Number(country.current_stake)) }); setClaiming(true); }
  const progress = Math.round((claimed / Math.max(countryFeatures.length, 1)) * 100);
  return <main className="min-h-screen bg-[#f3f0e8] text-[#111]">
    <header className="border-b border-black/[.07]"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-5"><div className="text-[11px] font-bold tracking-[-.02em]">GlobeBid<span className="text-[#6f63ff]">.world</span></div><nav className="flex items-center gap-5 text-[10px] font-medium text-black/50"><a href="#globe" className="hidden hover:text-black sm:block">Explore</a><a href="#country-market" className="hidden hover:text-black sm:block">Market</a><a href="/faq" className="hidden hover:text-black sm:block">FAQ</a><a href="#globe" className="rounded-full bg-[#111] px-4 py-2 text-white shadow-sm">Claim country</a></nav></div></header>
    <section className="px-3 pb-24 pt-14 md:px-6 md:pt-16">
      <div className="mx-auto max-w-3xl text-center">
        <div className="inline-flex items-center gap-3 rounded-full bg-[#111] px-4 py-2 font-mono text-[9px] font-semibold uppercase tracking-[.12em] text-white shadow-lg"><span>{claimed} countries claimed</span><i className="h-3 w-px bg-white/20" /><span>{formatMoney(total)} live stake</span><i className="size-1.5 rounded-full bg-[#35d269]" /></div>
        <h1 className="mt-8 text-[clamp(2.8rem,6vw,5.35rem)] font-bold leading-[1.02] tracking-[-.06em] text-[#080807]">Put your brand<br /><span className="relative inline-block px-3">on the map.<svg aria-hidden className="pointer-events-none absolute -inset-x-3 -inset-y-2 h-[calc(100%+16px)] w-[calc(100%+24px)] overflow-visible" viewBox="0 0 300 100" preserveAspectRatio="none"><ellipse cx="150" cy="50" rx="145" ry="43" fill="none" stroke="#28784f" strokeWidth="3" strokeLinecap="round" transform="rotate(-2 150 50)" /><path d="M14 57C27 18 88 3 156 7" fill="none" stroke="#28784f" strokeWidth="1.2" strokeLinecap="round" opacity=".45" /></svg></span></h1>
        <p className="mx-auto mt-7 max-w-lg text-sm font-medium leading-relaxed text-black/72 md:text-base">Claim a country, plant your logo, and hold the spotlight until another brand moves ahead.</p>
        <div className="mx-auto mt-9 max-w-md"><div className="flex items-center justify-between text-[11px] font-semibold"><span>{claimed} / {countryFeatures.length} countries</span><span className="font-mono text-[9px] text-[#34a95d]">{progress}% claimed</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-black/8"><div className="h-full rounded-full bg-[#111] transition-all" style={{ width: `${progress}%` }} /></div></div>
        <div className="mx-auto mt-5 inline-flex flex-wrap items-center justify-center gap-x-4 gap-y-2 rounded-full bg-[#111] px-5 py-3 font-mono text-[8px] font-semibold uppercase tracking-[.13em] text-white shadow-[0_14px_30px_rgba(0,0,0,.13)]"><span className="inline-flex items-center gap-2"><i className="size-1.5 rounded-full bg-[#35d269]" />Live marketplace</span><i className="hidden h-3 w-px bg-white/20 sm:block" /><span>Countries from $5</span><i className="hidden h-3 w-px bg-white/20 sm:block" /><span>Top stake owns the spotlight</span></div>
      </div>
      <div id="globe" className="relative mx-auto mt-12 h-[660px] max-w-[1320px] overflow-hidden rounded-[32px] border border-black/[.09] bg-[#e9e5dc] shadow-[0_34px_85px_rgba(34,30,20,.17)] md:h-[820px] md:rounded-[40px]">
        <div className="pointer-events-none absolute inset-3 rounded-[25px] border border-white/55 md:inset-4 md:rounded-[30px]" />
        <div className="absolute left-5 top-5 z-10 rounded-full border border-black/8 bg-[#f8f5ee]/90 px-3 py-2 font-mono text-[8px] font-semibold uppercase tracking-[.12em] text-black/50 backdrop-blur-md md:left-7 md:top-7">Interactive Earth · Drag to rotate</div>
        <div className="absolute inset-0"><Globe states={states} selected={selected} onSelect={select} onInteract={analytics.globeInteracted} onBrandClick={(code) => { analytics.brandClicked(code); select(code); }} /></div>
        <div className="pointer-events-none absolute inset-x-0 bottom-5 z-10 text-center font-mono text-[8px] font-semibold uppercase tracking-[.16em] text-black/35">Select a country · Scroll to zoom</div>
        {current && <CountryPanel country={current} claiming={claiming} onClaim={() => openClaim(current)} setClaiming={setClaiming} onClose={() => setSelected(undefined)} onNotice={setNotice} />}
      </div>
      {notice && <div className="glass enter fixed left-1/2 top-20 z-50 -translate-x-1/2 rounded-full px-5 py-3 text-sm" onAnimationEnd={() => window.setTimeout(() => setNotice(""), 2500)}>{notice}</div>}
    </section>
    <MarketSection country={current} bidders={bidders} viewers={viewers} onClaim={() => current && openClaim(current)} />
    <HomepageFaq />
    <MinimalFooter />
  </main>;
}

function fetchGlobe(setter: React.Dispatch<React.SetStateAction<Record<string, CountryState>>>) { fetch("/api/globe").then((r) => r.ok ? r.json() : {}).then((data) => setter((s) => mergeGlobeStates(s, data))).catch(() => {}); }

// Realtime pushes refetch every country, but most fields are unchanged between ticks. Keeping
// unaffected country objects by reference (instead of always spreading a brand-new object) lets
// React's setState bail out of a re-render entirely when nothing the UI cares about actually moved,
// and avoids forcing the globe's expensive texture memo to recompute for unrelated updates.
function mergeGlobeStates(prev: Record<string, CountryState>, incoming: Record<string, CountryState>) {
  let changed = false; const next = { ...prev };
  for (const iso3 in incoming) { const row = incoming[iso3]; const old = prev[iso3]; if (!old || old.current_stake !== row.current_stake || old.centroid_lat !== row.centroid_lat || old.centroid_lng !== row.centroid_lng || old.brand?.logo_url !== row.brand?.logo_url || old.brand?.name !== row.brand?.name || old.brand?.website_url !== row.brand?.website_url) { next[iso3] = row; changed = true; } }
  return changed ? next : prev;
}

async function pollBidStatus(bidId: string, countryCode: string) { for (let attempt = 0; attempt < 12; attempt++) { try { const response = await fetch(`/api/bids/${bidId}/status`, { cache: "no-store" }); if (response.ok) { const bid = await response.json(); if (bid.status === "paid") { analytics.paymentSuccessViewed({ country_code: countryCode, amount: Number(bid.amount), became_leader: Boolean(bid.became_leader), bid_id: bidId }); return; } if (["failed", "cancelled", "refunded"].includes(bid.status)) return; } } catch {} await new Promise((resolve) => setTimeout(resolve, 2500)); } }

function MarketSection({ country, bidders, viewers, onClaim }: { country?: CountryState; bidders: Bidder[]; viewers: number; onClaim: () => void }) {
  return <section id="country-market" className="mx-auto min-h-[70vh] max-w-6xl scroll-mt-0 px-5 py-20 md:px-10 md:py-28">
    <div className="mb-12 max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-black/35">Live country market</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em] md:text-6xl">{country ? `${country.name} is in play.` : "Every country has a story."}</h2><p className="mt-4 text-black/48">{country ? "See who controls it, who is close behind, and how many people are watching right now." : "Select a country on the globe to see its owner, active bidders, challengers and live viewers."}</p></div>
    {country ? <div className="grid gap-4 md:grid-cols-3">
      <MarketCard eyebrow="Current owner">{country.brand ? <BrandLine name={country.brand.name} logo={country.brand.logo_url} sub={`${formatMoney(Number(country.current_stake))} controlling stake`} /> : <div><p className="text-2xl font-semibold">Unclaimed</p><p className="mt-2 text-sm text-black/42">Be the first brand here.</p></div>}</MarketCard>
      <MarketCard eyebrow="Watching now"><p className="text-5xl font-semibold tracking-[-.05em]">{viewers}</p><p className="mt-3 text-sm text-black/42">live {viewers === 1 ? "viewer" : "viewers"} on {country.name}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-medium"><i className="size-2 rounded-full bg-emerald-500" /> Live presence</span></MarketCard>
      <MarketCard eyebrow="Next move"><p className="text-3xl font-semibold tracking-[-.04em]">{formatMoney(getMinimumNextStake(Number(country.current_stake)))}</p><p className="mt-3 text-sm text-black/42">puts your brand in front.</p><button onClick={onClaim} className="mt-6 rounded-full bg-black px-5 py-3 text-sm font-semibold text-white hover:bg-black/80">Bid on {country.name}</button></MarketCard>
      <div className="rounded-[28px] border border-black/8 bg-white p-6 md:col-span-3 md:p-8"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.17em] text-black/35">The field</p><h3 className="mt-2 text-2xl font-semibold">Brands bidding for {country.name}</h3></div><span className="text-sm text-black/35">{bidders.length} {bidders.length === 1 ? "brand" : "brands"}</span></div><div className="mt-7 divide-y divide-black/8">{bidders.length ? bidders.map((bid, i) => <div key={bid.brand_id} className="flex items-center gap-4 py-4"><span className="w-5 text-sm text-black/30">{i + 1}</span><BrandLine name={bid.brand?.name || "Brand"} logo={bid.brand?.logo_url || ""} sub={i === 0 ? "Current leader" : `${formatMoney(Math.max(0, Number(country.current_stake) - Number(bid.total_amount)))} behind the leader`} /><strong className="ml-auto">{formatMoney(Number(bid.total_amount))}</strong></div>) : <p className="py-8 text-sm text-black/38">No bids yet. The first $5 claim takes the country.</p>}</div></div>
    </div> : <div className="grid gap-4 md:grid-cols-3">{["Current owner", "Watching now", "Active challengers"].map((label) => <div key={label} className="rounded-[28px] border border-black/8 bg-white p-7"><p className="text-xs font-semibold uppercase tracking-[.17em] text-black/30">{label}</p><div className="mt-10 h-3 w-2/3 rounded-full bg-black/6" /><div className="mt-3 h-3 w-1/3 rounded-full bg-black/4" /></div>)}</div>}
  </section>;
}
function MarketCard({ eyebrow, children }: { eyebrow: string; children: React.ReactNode }) { return <div className="min-h-64 rounded-[28px] border border-black/8 bg-white p-7"><p className="mb-8 text-xs font-semibold uppercase tracking-[.17em] text-black/35">{eyebrow}</p>{children}</div>; }
function BrandLine({ name, logo, sub }: { name: string; logo: string; sub: string }) { return <div className="flex min-w-0 items-center gap-3">{logo ? <img src={logo} alt="" className="size-12 shrink-0 rounded-2xl border border-black/8 bg-white object-cover" /> : <div className="size-12 shrink-0 rounded-2xl bg-black/5" />}<div className="min-w-0"><p className="truncate font-semibold">{name}</p><p className="mt-1 truncate text-sm text-black/42">{sub}</p></div></div>; }

function CountryPanel({ country, claiming, onClaim, setClaiming, onClose, onNotice }: { country: CountryState; claiming: boolean; onClaim: () => void; setClaiming: (v: boolean) => void; onClose: () => void; onNotice: (v: string) => void }) {
  const next = getMinimumNextStake(Number(country.current_stake)); return <aside className="glass enter safe-bottom absolute inset-x-3 bottom-12 z-30 max-h-[70dvh] overflow-y-auto rounded-[28px] p-5 md:inset-x-auto md:bottom-auto md:right-8 md:top-1/2 md:w-[390px] md:-translate-y-1/2 md:rounded-[30px] md:p-7"><div className="flex items-start justify-between"><div><div className="text-3xl">{flag(country.iso2)}</div><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em]">{country.name}</h2></div><button aria-label="Close" onClick={onClose} className="grid size-9 place-items-center rounded-full bg-black/5 text-black/45">×</button></div>{!claiming ? <div className="mt-6">{country.brand ? <><BrandLine name={country.brand.name} logo={country.brand.logo_url} sub={`${formatMoney(Number(country.current_stake))} staked`} /><a href={country.brand.website_url} target="_blank" rel="noreferrer" onClick={() => analytics.externalBrandVisit(country.iso3)} className="mt-4 inline-block text-sm font-semibold text-black/55 hover:text-black">Visit brand ↗</a></> : <><p className="text-lg text-black/45">Unclaimed</p><p className="mt-2 text-4xl font-semibold">{formatMoney(next)}</p></>}<button onClick={onClaim} className="mt-6 w-full rounded-full bg-black px-5 py-4 font-semibold text-white">Claim {country.name} · {formatMoney(next)}</button></div> : <ClaimForm country={country} amount={next} onBack={() => setClaiming(false)} onNotice={onNotice} />}</aside>;
}
function ClaimForm({ country, amount, onBack, onNotice }: { country: CountryState; amount: number; onBack: () => void; onNotice: (v: string) => void }) {
  const [logo, setLogo] = useState<File>(); const [preview, setPreview] = useState(""); const [busy, setBusy] = useState(false); const input = "mt-2 w-full rounded-2xl border border-black/10 bg-black/[.035] px-4 py-3.5 text-sm outline-none placeholder:text-black/25 focus:border-black/30";
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!logo) return onNotice("Choose a logo first"); const form = new FormData(e.currentTarget); const website = String(form.get("website") || ""); const isClaimed = Number(country.current_stake) > 0; const isReclaim = Boolean(country.brand && comparableHost(country.brand.website_url) === comparableHost(website)); analytics.claimFormCompleted({ country_code: country.iso3, amount, is_claimed: isClaimed }); analytics.checkoutClicked({ country_code: country.iso3, amount, is_claimed: isClaimed, is_reclaim_attempt: isReclaim }); setBusy(true); let uploadComplete = false; try { const upload = new FormData(); upload.set("logo", await resizeImageFile(logo)); const up = await fetch("/api/upload", { method: "POST", body: upload }); const upJson = await up.json(); if (!up.ok) throw new Error(upJson.error || `upload_${up.status}`); uploadComplete = true; analytics.logoUploadSucceeded({ country_code: country.iso3, file_type: logo.type, file_size_bucket: fileSizeBucket(logo.size) }); const params = new URLSearchParams(location.search); const attribution = Object.fromEntries(["utm_source", "utm_medium", "utm_campaign", "utm_content", "utm_term"].map((key) => [key, params.get(key)]).filter((entry): entry is [string, string] => Boolean(entry[1]))); const response = await fetch("/api/checkout", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ country: country.iso3, amount, analyticsDistinctId: analytics.getDistinctId(), attribution, brand: { name: form.get("name"), websiteUrl: website, tagline: form.get("tagline"), logoUrl: upJson.url } }) }); const data = await response.json(); if (!response.ok) { analytics.checkoutCreateFailed({ country_code: country.iso3, amount, error_code: String(data.error || response.status) }); throw new Error(data.error); } location.href = data.checkoutUrl; } catch (error) { if (!uploadComplete) analytics.logoUploadFailed({ country_code: country.iso3, error_type: error instanceof Error ? error.message.slice(0, 80) : "unknown" }); onNotice(error instanceof Error ? error.message : "Checkout could not start"); setBusy(false); } }
  return <form onSubmit={submit} onFocus={() => analytics.claimFormStarted({ country_code: country.iso3, minimum_next_stake: amount })} className="mt-5"><button type="button" onClick={onBack} className="mb-4 text-sm text-black/45">← Country details</button><label className="block text-xs text-black/48">Website or X profile<input required data-ph-mask name="website" placeholder="yourstartup.com or @username" className={input} /></label><label className="mt-4 block text-xs text-black/48">Brand name<input required data-ph-mask maxLength={60} name="name" placeholder="Acme" className={input} /></label><label className="mt-4 block text-xs text-black/48">Logo<div className="mt-2 flex items-center gap-3"><label className="flex h-16 flex-1 cursor-pointer items-center rounded-2xl border border-dashed border-black/15 bg-black/[.025] px-4 text-sm text-black/38"><input className="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => { const f = e.target.files?.[0]; if (f) { setLogo(f); setPreview(URL.createObjectURL(f)); } }} />{logo?.name || "Choose PNG, JPG or WebP"}</label>{preview && <img src={preview} alt="Preview" className="size-16 rounded-2xl bg-white object-cover" />}</div></label><label className="mt-4 block text-xs text-black/48">Tagline (optional)<input data-ph-mask maxLength={80} name="tagline" placeholder="What do you make?" className={input} /></label><button disabled={busy} className="mt-5 w-full rounded-full bg-black px-5 py-4 font-semibold text-white disabled:opacity-50">{busy ? "Preparing checkout…" : `Continue to payment · ${formatMoney(amount)}`}</button></form>;
}

function comparableHost(value: string) { try { return new URL(/^https?:\/\//i.test(value) ? value : `https://${value}`).hostname.replace(/^www\./, "").toLowerCase(); } catch { return value.trim().toLowerCase(); } }
